/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as carbonAssets from "./CarbonAssets";
export type { carbonAssets };
import type * as prediction from "./Prediction";
export type { prediction };
