/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as proxySol from "./proxy.sol";
export type { proxySol };
import type * as proxyCctSol from "./proxyCCT.sol";
export type { proxyCctSol };
import type * as proxyCdcSol from "./proxyCDC.sol";
export type { proxyCdcSol };
import type * as proxyPccSol from "./proxyPCC.sol";
export type { proxyPccSol };
