/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IBlackListInterface extends Interface {
  getFunction(
    nameOrSignature: "addBlackList" | "getBlackListStatus" | "removeBlackList"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addBlackList",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBlackListStatus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeBlackList",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addBlackList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBlackListStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeBlackList",
    data: BytesLike
  ): Result;
}

export interface IBlackList extends BaseContract {
  connect(runner?: ContractRunner | null): IBlackList;
  waitForDeployment(): Promise<this>;

  interface: IBlackListInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addBlackList: TypedContractMethod<
    [_evilUser: AddressLike],
    [void],
    "nonpayable"
  >;

  getBlackListStatus: TypedContractMethod<
    [_user: AddressLike],
    [boolean],
    "view"
  >;

  removeBlackList: TypedContractMethod<
    [_clearedUser: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addBlackList"
  ): TypedContractMethod<[_evilUser: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBlackListStatus"
  ): TypedContractMethod<[_user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "removeBlackList"
  ): TypedContractMethod<[_clearedUser: AddressLike], [void], "nonpayable">;

  filters: {};
}
