/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cmcSol from "./cmc.sol";
export type { cmcSol };
import type * as polyv3Sol from "./polyv3.sol";
export type { polyv3Sol };
import type * as proxySol from "./proxy.sol";
export type { proxySol };
