/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as proxySol from "./proxy.sol";
export * as proxyCctSol from "./proxyCCT.sol";
export * as proxyCdcSol from "./proxyCDC.sol";
export * as proxyPccSol from "./proxyPCC.sol";
